add_subdirectory(core)
add_subdirectory(util)
add_subdirectory(ops)
if(${PROJECT_NAME_UPPER}_ENABLE_CUDA)
    add_subdirectory(cvcuda)
endif()
if(${PROJECT_NAME_UPPER}_ENABLE_CUDA AND ${PROJECT_NAME_UPPER}_BUILD_TENSORRT)
    add_subdirectory(model)
    add_subdirectory(engine)
    add_subdirectory(features)
endif()
if(${PROJECT_NAME_UPPER}_BUILD_PYTHON AND ${PROJECT_NAME_UPPER}_ENABLE_CUDA
   AND ${PROJECT_NAME_UPPER}_BUILD_TENSORRT)
    add_subdirectory(python)
endif()
