set(Faiss_VERSION "1.14.2")
set(Faiss_HOME "/home/pc/workspace/faiss-1.14.2/install" CACHE PATH "faiss" FORCE)
set(Faiss_LIBRARY_DIR "${Faiss_HOME}/lib")
set(Faiss_INCLUDE_DIRS "${Faiss_HOME}/include")
set(Faiss_BIN_DIR "${Faiss_HOME}/bin")
set(MKL_ROOT "/opt/intel/oneapi/mkl/2026.0" CACHE PATH "Intel MKL installation root")
set(MKL_LIBRARY_DIR "${MKL_ROOT}/lib")
find_library(Faiss_LIB_RELEASE faiss HINTS ${Faiss_LIBRARY_DIR})
find_library(Faiss_LIB_DEBUG faissd HINTS ${Faiss_LIBRARY_DIR})
find_library(MKL_INTEL_LP64_LIB mkl_intel_lp64 HINTS ${MKL_LIBRARY_DIR})
find_library(MKL_GNU_THREAD_LIB mkl_gnu_thread HINTS ${MKL_LIBRARY_DIR})
find_library(MKL_CORE_LIB mkl_core HINTS ${MKL_LIBRARY_DIR})

set(Faiss_DEPENDENCY_LIBS)
foreach(_Faiss_DEPENDENCY_LIB IN ITEMS MKL_INTEL_LP64_LIB MKL_GNU_THREAD_LIB MKL_CORE_LIB)
    if(${_Faiss_DEPENDENCY_LIB})
        list(APPEND Faiss_DEPENDENCY_LIBS ${${_Faiss_DEPENDENCY_LIB}})
    endif()
endforeach()

set(Faiss_LIBS)
if(Faiss_LIB_RELEASE AND Faiss_LIB_DEBUG)
    list(APPEND Faiss_LIBS debug ${Faiss_LIB_DEBUG} optimized ${Faiss_LIB_RELEASE} ${Faiss_DEPENDENCY_LIBS})
elseif(Faiss_LIB_RELEASE)
    list(APPEND Faiss_LIBS ${Faiss_LIB_RELEASE} ${Faiss_DEPENDENCY_LIBS})
elseif(Faiss_LIB_DEBUG)
    list(APPEND Faiss_LIBS ${Faiss_LIB_DEBUG} ${Faiss_DEPENDENCY_LIBS})
endif()
