set(Faiss_VERSION "1.7.4")
set(Faiss_HOME "D:/Software/dev/Faiss-1.7.4")
set(Faiss_LIBRARY_DIR "${Faiss_HOME}/lib")
set(Faiss_INCLUDE_DIRS "${Faiss_HOME}/include")
set(Faiss_BIN_DIR "${Faiss_HOME}/bin")
find_library(Faiss_LIB_RELEASE faiss HINTS ${Faiss_LIBRARY_DIR})
find_library(Faiss_LIB_DEBUG faissd HINTS ${Faiss_LIBRARY_DIR})

set(Faiss_LIBS)
if(Faiss_LIB_RELEASE AND Faiss_LIB_DEBUG)
    list(APPEND Faiss_LIBS debug ${Faiss_LIB_DEBUG} optimized ${Faiss_LIB_RELEASE})
elseif(Faiss_LIB_RELEASE)
    list(APPEND Faiss_LIBS ${Faiss_LIB_RELEASE})
elseif(Faiss_LIB_DEBUG)
    list(APPEND Faiss_LIBS ${Faiss_LIB_DEBUG})
endif()
