include(CMakePackageConfigHelpers)

if(NOT DEFINED INFERRT_INSTALL_CMAKEDIR)
    set(INFERRT_INSTALL_CMAKEDIR "lib/cmake/${PROJECT_NAME}" CACHE STRING "InferRT CMake package install directory")
endif()

install(EXPORT ${PROJECT_NAME}Targets
    FILE "${PROJECT_NAME}Targets.cmake"
    NAMESPACE ${PROJECT_NAME}::
    DESTINATION "${INFERRT_INSTALL_CMAKEDIR}"
)

configure_package_config_file(
    "${CMAKE_CURRENT_LIST_DIR}/${PROJECT_NAME}Config.cmake.in"
    "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
    INSTALL_DESTINATION "${INFERRT_INSTALL_CMAKEDIR}"
)

write_basic_package_version_file(
    "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}ConfigVersion.cmake"
    VERSION "${PROJECT_VERSION}"
    COMPATIBILITY SameMajorVersion
)

set(_INFERRT_PACKAGE_CONFIG_FILES
    "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
    "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}ConfigVersion.cmake"
)

if(${PROJECT_NAME_UPPER}_ENABLE_CUDA AND ${PROJECT_NAME_UPPER}_BUILD_TENSORRT)
    list(APPEND _INFERRT_PACKAGE_CONFIG_FILES "${CMAKE_CURRENT_LIST_DIR}/FindTensorRT.cmake")
endif()

if(Faiss_FOUND)
    list(APPEND _INFERRT_PACKAGE_CONFIG_FILES "${CMAKE_CURRENT_LIST_DIR}/ConfigFaiss.cmake")
    list(APPEND _INFERRT_PACKAGE_CONFIG_FILES "${CMAKE_CURRENT_LIST_DIR}/ConfigDependencyDefaults.cmake")
endif()

if(${PROJECT_NAME_UPPER}_BUILD_ONNX)
    list(APPEND _INFERRT_PACKAGE_CONFIG_FILES "${CMAKE_CURRENT_LIST_DIR}/ConfigONNXRuntime.cmake")
endif()

if(${PROJECT_NAME_UPPER}_BUILD_OPENVINO)
    list(APPEND _INFERRT_PACKAGE_CONFIG_FILES "${CMAKE_CURRENT_LIST_DIR}/ConfigOpenVINO.cmake")
endif()

install(FILES ${_INFERRT_PACKAGE_CONFIG_FILES} DESTINATION "${INFERRT_INSTALL_CMAKEDIR}")
